args = commandArgs(T)
infile = args[1]
title = sprintf("Gene Expression between %s and %s", args[2],args[3])
pdffile = sprintf("%s_vs_%s.cor.pdf", args[2],args[3])
pngfile = sprintf("%s_vs_%s.cor.png", args[2],args[3])

d <- read.table(infile, sep = "\t",stringsAsFactor=F,header=T)

library(ggplot2)
library(grid)
print('loaded packages')
colA = paste(args[2], '_FPKM', sep='')
colB = paste(args[3], '_FPKM', sep='')
print('col rename')
print(names(d))
B <- cor(d[,colA], d[,colB], method = c("spearman"))
C <- cor(d[,colA], d[,colB], method = c("pearson"))
print('cor')
linefit <-lm(d[,colA] ~ d[,colB])
B=round(B,4)
C=round(C,4)
linefit$coefficients[[2]]=sprintf("%.4f",linefit$coefficients[[2]])
print('darwing')
#pdf(pdffile)
p = ggplot(data = d, mapping = aes(x = log10(get(colA)), y = log10(get(colB)))) 
p1 = p + geom_point(colour="#B1639F",size=1)
p2 = p1 + xlab(sprintf("log10($s)",colA))+ylab(sprintf("log10(%s)",colB)) + ggtitle(title)
p3 = p2+ theme(axis.text=element_text(size=10),axis.title = element_text(size =13), plot.title=element_text(size=16),legend.title=element_text(size=14,face="plain"),legend.title.align=0,legend.key=element_blank(),legend.text=element_blank(),legend.position=c(0.18,0.92),legend.key.size=unit(0,"cm"))
p4 = p3 + geom_text(data=NULL, x=-1, y=3.5,label=paste(paste(" slope k = ",linefit$coefficients[[2]],"\n"),paste("spearman r = ",B,"\n"),paste("pearson r = ",C)),size=3)
p5 = p4 + stat_abline(colour="#A2A3A4",linetype="dashed",lw=0.6)
ggsave(p5, file=pdffile)
ggsave(p5, file=pngfile)
#dev.off()
#png(pngfile,600,600)
#p = ggplot(data = d, mapping = aes(x = log10(get(colA)), y = log10(get(colB))))
#p1 = p + geom_point(colour="#B1639F",size=1)
#p2 = p1 + xlab(sprintf("log10(%s)", colA)) + ylab(sprintf("log10(%s)", colB)) + ggtitle(title)
#p3 = p2 + + theme(axis.text=element_text(size=10),axis.title = element_text(size =13), plot.title=element_text(size=16),legend.title=element_text(size=14,face="plain"),legend.title.align=0,legend.key=element_blank(),legend.text=element_blank(),legend.position=c(0.18,0.92),legend.key.size=unit(0,"cm")) 
#p4 = p3 + geom_text(data=NUll, x=-1, y=3.5,label=paste(paste(" slope k = ",linefit$coefficients[[2]],"\n"),paste("spearman r = ",B,"\n"),paste("pearson r = ",C)), size =3)
#p5 = p4 + stat_abline(colour="#A2A3A4",linetype="dashed",lw=0.6)
#dev.off()
